### ISSUE TITLE
 AWS Lambdaを設定するまでの手順など

### ISSUE THREAD

**Issue by yosh1** [hackjapan/amazonconnect_slack#1]
@koyamaps 
初めまして。
私は AWS Lambda、Amazon connect共にあまり詳しくありません。
初心者でもわかるようなドキュメントや手順が乗っている参考になりそうなWEBサイトなどがありましたら教えていただくことはできませんでしょうか？
よろしくお願いいたします。

**Comment by koyamaps** [comment]
Amazon ConnectにおけるLambda関数の設定についてはこちらをご覧頂くと一般的な内容は掲載されているかと思います。
https://docs.aws.amazon.com/ja_jp/connect/latest/adminguide/connect-lambda-functions.html

また、こちらの classmethod さんが書いて頂いている記事は非常に参考になりますので、合わせて設定をされる際やカスタマイズされる際のチュートリアルにご利用ください。
https://dev.classmethod.jp/cloud/aws/amazon-connect-lambda/

**Comment by JenyaWP** [comment]
@koyamaps 
初めまして。
コードの中に「AMAZON_URL」環境変数が入っていますが、READMEに説明はありません。
その環境変数の設定する必要があるかどうか教えていただけませんか。
よろしくお願いします

**Comment by koyamaps** [comment]
@JenyaWP 
Python ファイル内に書かれています以下が .env 環境変数になります。
もし、この環境変数の設定以外の部分で設定でお困りでしたら、ログとスクリーンショットをセットで提供していただきますと、READMEをご報告頂いた内容と解決策をセットでアップデートさせて頂ければと思います。
```
 SLACK_WEBHOOK = os.environ['SLACK_WEBHOOK']
 SLACK_CHANNEL = os.environ['SLACK_CHANNEL']
 AMAZON_URL = os.environ['AMAZON_URL']
```

**Comment by JenyaWP** [comment]
お世話になっております。
導入できておりました！ありがとうございます！
よろしくお願いいたします。
